# Book settings
title: My sample book
author: The Jupyter Book Community
logo: logo.png

latex:
  latex_documents:
    targetname: book.tex

sphinx:
  extra_extensions:
    - sphinxcontrib.prettyproof
